name             'ele-cassandra'
maintainer       'Gaurav Bajaj'
maintainer_email 'gaurav.bajaj@rackspace.com'
license          'Rackspace'
description      'Installs/Configures ele-cassandra'
long_description 'Installs/Configures ele-cassandra'
version          '0.1.0'
depends          'cassandra-dse'
depends          'python'
